name: 'trigger-branch'
triggers:
- branches: ['feature/*']
steps:
- name: 'gcr.io/cloud-builders/go1'
  args: ['install', '.']
  env: ['PROJECT_ROOT=hello']
  triggers:
  - branches: ['feature/newAPI']
  - includedFiles: ['./has/*']
- name: 'should be removed'
  triggers:
  - includedFiles: ['./*/test']
- name: 'gcr.io/cloud-builders/go3'
  args: ['build', 'hello']
  env: ['PROJECT_ROOT=hello']
artifacts:
  objects:
    location: 'gs://$PROJECT_ID/'
    paths: ['hello']
---
name: 'trigger-tag'
triggers:
- tags: ['v1\..\.1']
steps:
- name: 'gcr.io/cloud-builders/go1'
  args: ['install', '.']
  env: ['PROJECT_ROOT=hello']
- name: 'should be removed'
  triggers:
  - ingnoredFiles: ['README.md']
- name: 'gcr.io/cloud-builders/go3'
  args: ['install', '.']
  env: ['PROJECT_ROOT=hello']
  triggers:
- tags: ['v1\..\.1']
artifacts:
  objects:
    location: 'gs://$PROJECT_ID/'
    paths: ['hello']
---
name: 'trigger-pullrequest'